
#ifndef FIREALARM_INTERFACE_H_
#define FIREALARM_INTERFACE_H_

typedef enum {
	SYSTEM_FINE,
	SYSTEM_HEAT,
	SYSTEM_FIRE,
	SYSTEM_FIRE_FINE,
	SYSTEM_NEWPASS
}System_Status_t;

#endif /* FIREALARM_INTERFACE_H_ */
